/**** 
============================================== 
= 		  REQUETES GENERES					 = 
============================================== 
***/ 

<!--Creation du planning salarie de la semaine 12 pour l'employé CECILE BELLEGUIC --> 
INSERT INTO planning_salarie(id_salarie,id_planning_point_vente,termine) VALUES ( select id_salarie from contrat where numero_contrat like 291,select id_planning_point_vente from planning_point_vente where id_point_vente in (select id_point_vente from point_vente where numero_point_vente like MS040114) and date_debut = '20/03/2017',true);

<!-- Création de l'évenement Hebdo de l'employe CECILE BELLEGUICpour la semaine du 12 --> 
insert into ev_hebdo(id_planning_salarie,id_element,code_element,valeur) values (select id_planning_salarie from planning_salarie where id_salarie in (select id_salarie from contrat where numero_contrat like 291) and id_planning_point_vente in (select id_planning_point_vente from planning_point_vente where id_point_vente in (select id_point_vente from point_vente where numero_point_vente like MS040114 ) and date_debut = '20/03/2017'), '000', 'CODE','000');

<!-- Planing plage pour chaque jour de la semaine 12 pour l'employe CECILE BELLEGUIC dont la date de debut est 23/03/2017 et la date de fin est 23/03/2017 -->
insert into planning_plage (debut,fin,id_motif,unite,duree_semaine_0,id_salarie,id_point_vente) values ('23/03/2017','23/03/2017',34,'H',select id_salarie from contrat where numero_contrat like 291,select id_point_vente from point_vente where numero_point_vente like 'MS040114');
<!-- Requete pour tous les jours de la semaine 12 pour l'employé CECILE BELLEGUIC  -->

insert into planning_jour (id_planning_salarie,date,id_planning_type_jour,contractuel,id_planning_plage,unite,presence_matin,presence_apm,type_contenu,heures_effectuees) values (select id_planning_salarie from planning_salarie where id_salarie in (select id_salarie from contrat where numero_contrat like 291 and id_planning_point_vente in (select id_planning_point_vente from planning_point_vente where id_point_vente in (select id_point_vente from point_vente where numero_point_vente like 'MS040114') and date_debut = '20/03/2017')),'20/03/2017',select id_planning_type_jour from planning_type_jour where numero_jour=0 and id_planning_type in (select id_planning_type from planning_type where id_contrat in (select id_contrat from  contrat where numero_contrat like 291) and debut <='20/03/2017' and fin is null),select contractuel from planning_type_jour where numero_jour=0 and id_planning_type in (select id_planning_type from planning_type where id_contrat in (select id_contrat from  contrat where numero_contrat like '291') and debut <='20/03/2017' and fin is null),select id_planning_plage from planning_plage where debut ='20/03/2017' and id_point_vente in (select id_point_vente from point_vente where numero_point_vente like 'MS040114')and id_salarie in (select id_salarie from contrat where numero_contrat like '291') and id_point_vente in (select id_point_vente from point_vente where numero_point_vente like 'MS040114'),'H',-1,-1,'N',19800000);
insert into planning_jour (id_planning_salarie,date,id_planning_type_jour,contractuel,id_planning_plage,unite,presence_matin,presence_apm,type_contenu,heures_effectuees) values (select id_planning_salarie from planning_salarie where id_salarie in (select id_salarie from contrat where numero_contrat like 291 and id_planning_point_vente in (select id_planning_point_vente from planning_point_vente where id_point_vente in (select id_point_vente from point_vente where numero_point_vente like 'MS040114') and date_debut = '20/03/2017')),'21/03/2017',select id_planning_type_jour from planning_type_jour where numero_jour=1 and id_planning_type in (select id_planning_type from planning_type where id_contrat in (select id_contrat from  contrat where numero_contrat like 291) and debut <='20/03/2017' and fin is null),select contractuel from planning_type_jour where numero_jour=1 and id_planning_type in (select id_planning_type from planning_type where id_contrat in (select id_contrat from  contrat where numero_contrat like '291') and debut <='20/03/2017' and fin is null),select id_planning_plage from planning_plage where debut ='20/03/2017' and id_point_vente in (select id_point_vente from point_vente where numero_point_vente like 'MS040114')and id_salarie in (select id_salarie from contrat where numero_contrat like '291') and id_point_vente in (select id_point_vente from point_vente where numero_point_vente like 'MS040114'),'H',-1,-1,'N',14400000);
insert into planning_jour (id_planning_salarie,date,id_planning_type_jour,contractuel,id_planning_plage,unite,presence_matin,presence_apm,type_contenu,heures_effectuees) values (select id_planning_salarie from planning_salarie where id_salarie in (select id_salarie from contrat where numero_contrat like 291 and id_planning_point_vente in (select id_planning_point_vente from planning_point_vente where id_point_vente in (select id_point_vente from point_vente where numero_point_vente like 'MS040114') and date_debut = '20/03/2017')),'22/03/2017',select id_planning_type_jour from planning_type_jour where numero_jour=2 and id_planning_type in (select id_planning_type from planning_type where id_contrat in (select id_contrat from  contrat where numero_contrat like 291) and debut <='20/03/2017' and fin is null),select contractuel from planning_type_jour where numero_jour=2 and id_planning_type in (select id_planning_type from planning_type where id_contrat in (select id_contrat from  contrat where numero_contrat like '291') and debut <='20/03/2017' and fin is null),select id_planning_plage from planning_plage where debut ='20/03/2017' and id_point_vente in (select id_point_vente from point_vente where numero_point_vente like 'MS040114')and id_salarie in (select id_salarie from contrat where numero_contrat like '291') and id_point_vente in (select id_point_vente from point_vente where numero_point_vente like 'MS040114'),'H',-1,-1,'N',14400000);
insert into planning_jour (id_planning_salarie,date,id_planning_type_jour,contractuel,id_planning_plage,unite,presence_matin,presence_apm,type_contenu,heures_effectuees) values (select id_planning_salarie from planning_salarie where id_salarie in (select id_salarie from contrat where numero_contrat like 291 and id_planning_point_vente in (select id_planning_point_vente from planning_point_vente where id_point_vente in (select id_point_vente from point_vente where numero_point_vente like 'MS040114') and date_debut = '20/03/2017')),'24/03/2017',select id_planning_type_jour from planning_type_jour where numero_jour=4 and id_planning_type in (select id_planning_type from planning_type where id_contrat in (select id_contrat from  contrat where numero_contrat like 291) and debut <='20/03/2017' and fin is null),select contractuel from planning_type_jour where numero_jour=4 and id_planning_type in (select id_planning_type from planning_type where id_contrat in (select id_contrat from  contrat where numero_contrat like '291') and debut <='20/03/2017' and fin is null),select id_planning_plage from planning_plage where debut ='20/03/2017' and id_point_vente in (select id_point_vente from point_vente where numero_point_vente like 'MS040114')and id_salarie in (select id_salarie from contrat where numero_contrat like '291') and id_point_vente in (select id_point_vente from point_vente where numero_point_vente like 'MS040114'),'H',-1,-1,'N',18900000);
insert into planning_jour (id_planning_salarie,date,id_planning_type_jour,contractuel,id_planning_plage,unite,presence_matin,presence_apm,type_contenu,heures_effectuees) values (select id_planning_salarie from planning_salarie where id_salarie in (select id_salarie from contrat where numero_contrat like 291 and id_planning_point_vente in (select id_planning_point_vente from planning_point_vente where id_point_vente in (select id_point_vente from point_vente where numero_point_vente like 'MS040114') and date_debut = '20/03/2017')),'25/03/2017',select id_planning_type_jour from planning_type_jour where numero_jour=5 and id_planning_type in (select id_planning_type from planning_type where id_contrat in (select id_contrat from  contrat where numero_contrat like 291) and debut <='20/03/2017' and fin is null),select contractuel from planning_type_jour where numero_jour=5 and id_planning_type in (select id_planning_type from planning_type where id_contrat in (select id_contrat from  contrat where numero_contrat like '291') and debut <='20/03/2017' and fin is null),select id_planning_plage from planning_plage where debut ='20/03/2017' and id_point_vente in (select id_point_vente from point_vente where numero_point_vente like 'MS040114')and id_salarie in (select id_salarie from contrat where numero_contrat like '291') and id_point_vente in (select id_point_vente from point_vente where numero_point_vente like 'MS040114'),'H',-1,-1,'N',12600000);
insert into planning_jour (id_planning_salarie,date,id_planning_type_jour,contractuel,id_planning_plage,unite,presence_matin,presence_apm,type_contenu,heures_effectuees) values (select id_planning_salarie from planning_salarie where id_salarie in (select id_salarie from contrat where numero_contrat like 291 and id_planning_point_vente in (select id_planning_point_vente from planning_point_vente where id_point_vente in (select id_point_vente from point_vente where numero_point_vente like 'MS040114') and date_debut = '20/03/2017')),'26/03/2017',select id_planning_type_jour from planning_type_jour where numero_jour=6 and id_planning_type in (select id_planning_type from planning_type where id_contrat in (select id_contrat from  contrat where numero_contrat like 291) and debut <='20/03/2017' and fin is null),select contractuel from planning_type_jour where numero_jour=6 and id_planning_type in (select id_planning_type from planning_type where id_contrat in (select id_contrat from  contrat where numero_contrat like '291') and debut <='20/03/2017' and fin is null),select id_planning_plage from planning_plage where debut ='20/03/2017' and id_point_vente in (select id_point_vente from point_vente where numero_point_vente like 'MS040114')and id_salarie in (select id_salarie from contrat where numero_contrat like '291') and id_point_vente in (select id_point_vente from point_vente where numero_point_vente like 'MS040114'),'H',-2,-2,'N',null);
insert into planning_jour (id_planning_salarie,date,id_planning_type_jour,contractuel,id_planning_plage,unite,presence_matin,presence_apm,type_contenu,heures_effectuees) values (select id_planning_salarie from planning_salarie where id_salarie in (select id_salarie from contrat where numero_contrat like 291 and id_planning_point_vente in (select id_planning_point_vente from planning_point_vente where id_point_vente in (select id_point_vente from point_vente where numero_point_vente like 'MS040114') and date_debut = '20/03/2017')),'23/03/2017',select id_planning_type_jour from planning_type_jour where numero_jour=6 and id_planning_type in (select id_planning_type from planning_type where id_contrat in (select id_contrat from  contrat where numero_contrat like 291) and debut <='20/03/2017' and fin is null),select contractuel from planning_type_jour where numero_jour=6 and id_planning_type in (select id_planning_type from planning_type where id_contrat in (select id_contrat from  contrat where numero_contrat like '291') and debut <='20/03/2017' and fin is null),select id_planning_plage from planning_plage where debut ='20/03/2017' and id_point_vente in (select id_point_vente from point_vente where numero_point_vente like 'MS040114')and id_salarie in (select id_salarie from contrat where numero_contrat like '291') and id_point_vente in (select id_point_vente from point_vente where numero_point_vente like 'MS040114'),'H',34,34,'A',null);
<!-- toutes les plages horaires du salarié CECILE BELLEGUIC pour de la semaine 12 -->
insert into plage_horaire(id_planning_jour,debut_plage, fin_plage, id_motif) values (select id_planning_jour from planning_jour where id_planning_salarie in (select id_planning_salarie from planning_salarie where id_salarie=291 and id_planning_point_vente in (select id_planning_point_vente from planning_point_vente where id_point_vente in (select id_point_vente from point_vente where numero_point_vente like 'MS040114') and date_debut = '20/03/2017') and date_debut ='20/03/2017'),'09:00','14:30','-1');
insert into plage_horaire(id_planning_jour,debut_plage, fin_plage, id_motif) values (select id_planning_jour from planning_jour where id_planning_salarie in (select id_planning_salarie from planning_salarie where id_salarie=291 and id_planning_point_vente in (select id_planning_point_vente from planning_point_vente where id_point_vente in (select id_point_vente from point_vente where numero_point_vente like 'MS040114') and date_debut = '20/03/2017') and date_debut ='20/03/2017'),'15:00','16:30','-1');
insert into plage_horaire(id_planning_jour,debut_plage, fin_plage, id_motif) values (select id_planning_jour from planning_jour where id_planning_salarie in (select id_planning_salarie from planning_salarie where id_salarie=291 and id_planning_point_vente in (select id_planning_point_vente from planning_point_vente where id_point_vente in (select id_point_vente from point_vente where numero_point_vente like 'MS040114') and date_debut = '20/03/2017') and date_debut ='20/03/2017'),'17:30','19:45','-1');
insert into plage_horaire(id_planning_jour,debut_plage, fin_plage, id_motif) values (select id_planning_jour from planning_jour where id_planning_salarie in (select id_planning_salarie from planning_salarie where id_salarie=291 and id_planning_point_vente in (select id_planning_point_vente from planning_point_vente where id_point_vente in (select id_point_vente from point_vente where numero_point_vente like 'MS040114') and date_debut = '20/03/2017') and date_debut ='21/03/2017'),'14:30','18:30','-1');
insert into plage_horaire(id_planning_jour,debut_plage, fin_plage, id_motif) values (select id_planning_jour from planning_jour where id_planning_salarie in (select id_planning_salarie from planning_salarie where id_salarie=291 and id_planning_point_vente in (select id_planning_point_vente from planning_point_vente where id_point_vente in (select id_point_vente from point_vente where numero_point_vente like 'MS040114') and date_debut = '20/03/2017') and date_debut ='22/03/2017'),'09:00','13:00',34);
insert into plage_horaire(id_planning_jour,debut_plage, fin_plage, id_motif) values (select id_planning_jour from planning_jour where id_planning_salarie in (select id_planning_salarie from planning_salarie where id_salarie=291 and id_planning_point_vente in (select id_planning_point_vente from planning_point_vente where id_point_vente in (select id_point_vente from point_vente where numero_point_vente like 'MS040114') and date_debut = '20/03/2017') and date_debut ='22/03/2017'),'14:30','18:30','-1');
insert into plage_horaire(id_planning_jour,debut_plage, fin_plage, id_motif) values (select id_planning_jour from planning_jour where id_planning_salarie in (select id_planning_salarie from planning_salarie where id_salarie=291 and id_planning_point_vente in (select id_planning_point_vente from planning_point_vente where id_point_vente in (select id_point_vente from point_vente where numero_point_vente like 'MS040114') and date_debut = '20/03/2017') and date_debut ='24/03/2017'),'14:00','19:15','-1');
insert into plage_horaire(id_planning_jour,debut_plage, fin_plage, id_motif) values (select id_planning_jour from planning_jour where id_planning_salarie in (select id_planning_salarie from planning_salarie where id_salarie=291 and id_planning_point_vente in (select id_planning_point_vente from planning_point_vente where id_point_vente in (select id_point_vente from point_vente where numero_point_vente like 'MS040114') and date_debut = '20/03/2017') and date_debut ='25/03/2017'),'09:30','13:00','-1');
insert into plage_horaire(id_planning_jour,debut_plage, fin_plage, id_motif) values (select id_planning_jour from planning_jour where id_planning_salarie in (select id_planning_salarie from planning_salarie where id_salarie=291 and id_planning_point_vente in (select id_planning_point_vente from planning_point_vente where id_point_vente in (select id_point_vente from point_vente where numero_point_vente like 'MS040114') and date_debut = '20/03/2017') and date_debut ='25/03/2017'),'14:00','19:15','-1');
insert into plage_horaire(id_planning_jour,debut_plage, fin_plage, id_motif) values (select id_planning_jour from planning_jour where id_planning_salarie in (select id_planning_salarie from planning_salarie where id_salarie=291 and id_planning_point_vente in (select id_planning_point_vente from planning_point_vente where id_point_vente in (select id_point_vente from point_vente where numero_point_vente like 'MS040114') and date_debut = '20/03/2017') and date_debut ='26/03/2017'),'','','-2');

<!-- pour tous les jours de la semaine du salarié CECILE BELLEGUIC -->
insert into ev_jour(id_planning_jour,id_element,code_element,valeur) values (select id_planning_jour from planning_jour where id_planning_salarie in (select id_planning_salarie from planning_salarie where id_salarie=291 and id_planning_point_vente in (select id_planning_point_vente from planning_point_vente where id_point_vente in (select id_point_vente from point_vente where numero_point_vente like 'MS040114') and date_debut ='20/03/2017')) and date = '20/03/2017','000','CODE','000');
insert into ev_jour(id_planning_jour,id_element,code_element,valeur) values (select id_planning_jour from planning_jour where id_planning_salarie in (select id_planning_salarie from planning_salarie where id_salarie=291 and id_planning_point_vente in (select id_planning_point_vente from planning_point_vente where id_point_vente in (select id_point_vente from point_vente where numero_point_vente like 'MS040114') and date_debut ='20/03/2017')) and date = '21/03/2017','000','CODE','000');
insert into ev_jour(id_planning_jour,id_element,code_element,valeur) values (select id_planning_jour from planning_jour where id_planning_salarie in (select id_planning_salarie from planning_salarie where id_salarie=291 and id_planning_point_vente in (select id_planning_point_vente from planning_point_vente where id_point_vente in (select id_point_vente from point_vente where numero_point_vente like 'MS040114') and date_debut ='20/03/2017')) and date = '22/03/2017','000','CODE','000');
insert into ev_jour(id_planning_jour,id_element,code_element,valeur) values (select id_planning_jour from planning_jour where id_planning_salarie in (select id_planning_salarie from planning_salarie where id_salarie=291 and id_planning_point_vente in (select id_planning_point_vente from planning_point_vente where id_point_vente in (select id_point_vente from point_vente where numero_point_vente like 'MS040114') and date_debut ='20/03/2017')) and date = '23/03/2017','000','CODE','000');
insert into ev_jour(id_planning_jour,id_element,code_element,valeur) values (select id_planning_jour from planning_jour where id_planning_salarie in (select id_planning_salarie from planning_salarie where id_salarie=291 and id_planning_point_vente in (select id_planning_point_vente from planning_point_vente where id_point_vente in (select id_point_vente from point_vente where numero_point_vente like 'MS040114') and date_debut ='20/03/2017')) and date = '24/03/2017','000','CODE','000');
insert into ev_jour(id_planning_jour,id_element,code_element,valeur) values (select id_planning_jour from planning_jour where id_planning_salarie in (select id_planning_salarie from planning_salarie where id_salarie=291 and id_planning_point_vente in (select id_planning_point_vente from planning_point_vente where id_point_vente in (select id_point_vente from point_vente where numero_point_vente like 'MS040114') and date_debut ='20/03/2017')) and date = '25/03/2017','000','CODE','000');
insert into ev_jour(id_planning_jour,id_element,code_element,valeur) values (select id_planning_jour from planning_jour where id_planning_salarie in (select id_planning_salarie from planning_salarie where id_salarie=291 and id_planning_point_vente in (select id_planning_point_vente from planning_point_vente where id_point_vente in (select id_point_vente from point_vente where numero_point_vente like 'MS040114') and date_debut ='20/03/2017')) and date = '26/03/2017','000','CODE','000');

